name: Automatic Tagging

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full tag history is available

      - name: Fetch all tags
        run: git fetch --tags --force

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          if [[ -z "$latest_tag" ]]; then
            latest_tag="v0.0.0"
          fi
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Calculate next version
        id: versioning
        run: |
          latest_tag="${{ env.latest_tag }}"
          version="${latest_tag#v}" # Remove "v" prefix
          IFS='.' read -r major minor patch <<< "$version"

          # Convert to integers
          major=$((major))
          minor=$((minor))
          patch=$((patch))

          # Increment patch version
          patch=$((patch + 1))

          # Reset and increment minor version if needed
          if [ "$patch" -ge 10 ]; then
            patch=0
            minor=$((minor + 1))
          fi

          # Reset and increment major version if needed
          if [ "$minor" -ge 10 ]; then
            minor=0
            major=$((major + 1))
          fi

          new_tag="v$major.$minor.$patch"

          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Create and push new tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

          # Ensure tag does not already exist before pushing
          if git rev-parse "refs/tags/${{ env.new_tag }}" >/dev/null 2>&1; then
            echo "Tag ${{ env.new_tag }} already exists, skipping tagging."
            exit 0
          fi

          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}
