name: Automatic Tagging

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Calculate next version
        id: versioning
        run: |
          latest_tag="${{ env.latest_tag }}"
          version="${latest_tag#v}" # Remove "v" prefix
          IFS='.' read -r major minor patch <<< "$version"

          # Convert to integers
          major=$((major))
          minor=$((minor))
          patch=$((patch))

          # Custom logic for version bumping
          if [ "$patch" -ge 10 ]; then
            patch=0
            minor=$((minor + 1))
          else
            patch=$((patch + 1))
          fi

          if [ "$minor" -ge 10 ]; then
            minor=0
            major=$((major + 1))
          fi

          new_tag="v$major.$minor.$patch"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Create and push new tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}
